# Generated by Django 3.1.1 on 2021-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0003_auto_20210308_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='top_proggamming_book',
            field=models.BooleanField(default=False),
        ),
    ]
