# Generated by Django 3.1.1 on 2021-03-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0004_book_top_proggamming_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk']},
        ),
    ]
